### PR TITLE
Collapse leaves and top half

### PR DESCRIPTION
**Pull request by cryptonemo**
Update store interface to allow configuration data to be passed to the implementation.
Add expected interface change for a new kind of store (not yet included).
Remove MmapStore (unused, as indicated elsewhere by @schomatis)

### CODE REVIEW

**Comment by dignifiedquire** [comment]
@schomatis please take a look, give you are most familiar with this current impl

**Comment by schomatis** [comment]
@cryptonemo This looks good but could we drop https://github.com/filecoin-project/merkle_light/pull/40/commits/900456cdaf535d0f3cbec7a56abd0bdc95d129eb from this PR to concentrate on the collapse of the two stores please?

**Comment by cryptonemo** [comment]
> @cryptonemo This looks good but could we drop [900456c](https://github.com/filecoin-project/merkle_light/commit/900456cdaf535d0f3cbec7a56abd0bdc95d129eb) from this PR to concentrate on the collapse of the two stores please?

Yes, that makes sense, I'll push that in a bit, thanks!

**Comment by cryptonemo** [comment]
@schomatis Updated.

**Comment by cryptonemo** [comment]
@schomatis Thanks, I'll push updates in a bit!

**Comment by cryptonemo** [comment]
@schomatis Updated.

**Pull request merged**
