### PR TITLE
feat: enable direct building of levelcache stores

### PR DESCRIPTION
**Pull request by cryptonemo**

### CODE REVIEW

**Comment by cryptonemo** [comment]
@dignifiedquire If this is urgent, it works and can be merged. Otherwise, I plan to add more tests and cleanups, etc.  Let me know if this PR should also include the removal of the v1/v2 compaction, etc as well like we discussed.  As-is, everything is backward compatible in terms of levelcache usage.

**Comment by dignifiedquire** [comment]
@cryptonemo if we want to make breaking changes in that front, we should get them in soon, likely sometime this week. No rush on getting this merged

**Comment by cryptonemo** [comment]
@dignifiedquire Not sure if this is what you're saying or opposing, but at this point, I think it's better to merge this separately, since it could be integrated/tested in rust-fil-proofs over time without impacting much else.  At some later point when that later work is merged and compaction is no longer used, it makes sense to rip that all out then.

**Comment by cryptonemo** [comment]
Thanks, I'll merge this shortly. In the meantime, I've started testing out the integration and want to make sure all is well first.  It's coming together, but quite there yet.  At the moment, I don't anticipate changes required here.  Just being cautious ;-)

**Pull request merged**
